title: IZItag
email: info@izitag.net
description: Designing Brands
url: "https://izitag.net"
author: "Ivo Zinenda"


# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-sitemap
  - jekyll-analytics
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - vendor

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

# Collections
collections:
  sobre:
  servicos:
  portfolio:

logo: /assets/img/brand/logo.svg
image: /assets/img/brand/logowhite.svg