title: IZITech
email: info@izitech.co
description: Desenvolvendo Soluções Digitais
url: "https://izitech.co"
author: "Ivo Zinenda"


# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  #- jekyll-feed
  - jekyll-email-protect
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - vendor

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

# Collections
collections_dir: collections
collections:
  sobre:
  clientes:
  servicos:
  portfolio_logotipos:
  portfolio_websites:
  portfolio_consultoria:
    output: true

logo: /assets/img/brand/IZIlogo.svg
image: /assets/img/brand/logowhite.svg

# Build settings
markdown: kramdown
permalink: pretty

paginate: 10