title: IZItag
email: info@izitag.site
description: Be Seen! Get Tagged!
url: "https://izitag.site" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-menus
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - vendor

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed