title: IZItag
email: info@izitag.site
description: Be Seen! Get Tagged!
url: "https://izitag.site" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - vendor

defaults:
  - scope:
        path: ""
        type: posts
    values:
        image: ""
  
  - scope:
        path: ""
        type: collection
    values:
        image_path: ""
        title: ""
        link: ""

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

# Collections
collections:
  servicos:
  web:
  logotipos:

logo: /assets/img/logo.svg
image: /assets/img/logo.svg