title: IZITech
email: info@izitech.co
description: Desenvolvendo Soluções Digitais
url: "https://izitech.co"
author: "Ivo Zinenda"


# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - node_modules
  - vendor

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

# Collections
collections_dir: collections
collections:
  sobre:
  clientes:
  servicos:
  portfolio_logotipos:
  portfolio_websites:
  portfolio_consultoria:
    output: true

logo: /assets/img/brand/IZIlogo.svg
image: /assets/img/brand/logowhite.svg

# Build settings
markdown: kramdown
permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 16
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2