backend:
  name: git-gateway

logo_url: 'https://d33wubrfki0l68.cloudfront.net/f1afd154dd1bd09e6957dce7291bfc56834b4489/b2edb/assets/img/brand/logo.svg'

collections:
  - label: "Sobre"
    name: "sobre"
    folder: "collections/_sobre"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Ícone", name: "icon", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}

  - label: "Serviços"
    name: "servicos"
    folder: "collections/_servicos"
    create: false
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Imagem"
        name: "image"
        widget: "image"
        media_library:
          name: cloudinary
          output_filename_only: true
      - {label: "Conteúdo", name: "body", widget: "markdown"}

  - label: "Clientes"
    name: "clientes"
    folder: "collections/_clientes"
    create: true
    fields:
      - {label: "Clientes", name: "title", default: "Clientes", widget: "string"}
      - label: "Cliente"
        name: "client"
        widget: "list"
        fields:
          - {label: "Empresa", name: "company", widget: "string"}
          - {label: "Logotipo", name: "image", widget: "image"}

  - label: "Portfólio - Websites"
    name: "portfolio_websites"
    folder: "collections/_portfolio_websites"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Link", name: "body", widget: "markdown"}

  - label: "Portfólio - Logotipos"
    name: "portfolio_logotipos"
    folder: "collections/_portfolio_logotipos"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}

  - label: "Portfólio - Consultoria"
    name: "portfolio_consultoria"
    folder: "collections/_portfolio_consultoria"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}

  - label: "Posts"
    name: "posts"
    folder: collections/_posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "category", widget: "string"}
      - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Corpo", name: "body", widget: "markdown"}